####################################################
#             ESPHOME CUSTOM COMPONENT             #
#                       FOR                        #
# KAMSTRUP MULTICAL 402/602 DISTRICT HEATING METER #
####################################################

#############################################
#   Substitutions section contains all the  #
# user/device specific configurable details #
#############################################
substitutions:
  device_name: multical402
  friendly_name: District Heating
  device_description: District Heating Multical 402
  platform: ESP8266
  board: d1_mini
  wifi: !secret wifi_ssid_tp
  password: !secret wifi_password_tp
  ip: !secret static_ip_multical402
  gateway: !secret gateway
  ha_api_key: !secret api_key
  ap_password: !secret wifi_ap_password
  ota_password: !secret multical402_ota_password
  # uart_tx: "1" # GPIO1 = D10 - TX pin for hardware UART on ESP8266
  # uart_rx: "3" # GPIO3 = D9  - TX pin for hardware UART on ESP8266
  uart_tx: "5" # GPIO5 = D1 - Typical TX pin for software UART on ESP8266
  uart_rx: "4" # GPIO4 = D2 - Typical RX pin for software UART on ESP8266
  # uart_tx: "17" # GPIO17 = D27 - Default TX pin for hardware UART#2 on ESP32 modules
  # uart_rx: "16" # GPIO16 = D25 - Default RX pin for hardware UART#2 on ESP32 modules
  stop_bit: "2" # Set to 2 for Multical 602 and to 1 for Multical 402 meter.
  update_millis: "600000" # Update interval in milliseconds (10 min. interval)

  
###############################################
#               Main YAML block               #
# You should not need to edit below this line #
############################################### 
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${device_description}
  platform: ${platform}
  board: ${board}
  includes:
    - kmp.h
    - multical402.h


#Multical UART
uart:
  - id: uart_bus
    tx_pin: ${uart_tx}
    rx_pin: ${uart_rx}
    baud_rate: 1200
    data_bits: 8
    parity: NONE
    # Multical 402 uses 1 stop bit
    # Multical 602 uses 2 stop bits
    stop_bits: ${stop_bit}
    #debug:

# Enable logging
logger:

  
# Enable Home Assistant API
api:
  encryption:
    key: ${ha_api_key}


ota:
  password: ${ota_password}


wifi:
  ssid: ${wifi}
  password: ${password}
  fast_connect: true
  manual_ip:
    static_ip: ${ip}
    gateway: ${gateway}
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case WiFi connection fails
  ap:
    ssid: ${friendly_name} FB Hotspot
    password: ${ap_password}


captive_portal:


web_server:
  port: 80


# Multical Custom Sensor (first variable is update interval in ms; 3600000 is 1 hour)
# Set to 600000 ms = 10 min. update interval
custom_component:
  - lambda: |-
      auto multical402 = new Multical402(
        ${update_millis},
        id(uart_bus),
        id(m_energy),
        id(m_power),
        id(m_tin),
        id(m_tout),
        id(m_tdiff),
        id(m_flow),
        id(m_volume));
      App.register_component(multical402);
      return {multical402};
    components:
      - id: multical


binary_sensor:
  - platform: status
    name: "Node status"
  

sensor:
# Uptime sensor / WiFi strength in db and percentage
- platform: uptime
  name: "Uptime sensor"

- platform: wifi_signal
  id: wifi_strength_db
  name: "WiFi strength db"
  update_interval: 60s
  entity_category: "diagnostic"

# Reports the WiFi signal strength in percentage
- platform: copy
  source_id: wifi_strength_db
  name: "WiFi strength pct."
  filters:
    - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
  unit_of_measurement: "%"
  entity_category: "diagnostic"

# Multical Custom Sensors
- name: "Multical Energy"
  platform: template
  id: m_energy
  icon: "mdi:lightning-bolt"
  unit_of_measurement: MWh
  accuracy_decimals: 3
  state_class: "total_increasing"
  device_class: "energy"

- name: "Multical Volume"
  platform: template
  id: m_volume
  unit_of_measurement: m3
  accuracy_decimals: 2
  state_class: "measurement"

- name: "Multical Temperature In"
  platform: template
  id: m_tin
  icon: "mdi:thermometer"
  unit_of_measurement: °C
  accuracy_decimals: 2
  state_class: "measurement"
  device_class: "temperature"

- name: "Multical Temperature Out"
  platform: template
  id: m_tout
  icon: "mdi:thermometer"
  unit_of_measurement: °C
  accuracy_decimals: 2
  state_class: "measurement"
  device_class: "temperature"

- name: "Multical Temperature Diff"
  platform: template
  id: m_tdiff
  icon: "mdi:thermometer"
  unit_of_measurement: °C
  accuracy_decimals: 2
  state_class: "measurement"
  device_class: "temperature"

- name: "Multical Power"
  platform: template
  id: m_power
  icon: "mdi:flash"
  unit_of_measurement: kW
  accuracy_decimals: 1
  state_class: "measurement"
  device_class: "power"

- name: "Multical Flow"
  platform: template
  id: m_flow
  unit_of_measurement: l/h
  accuracy_decimals: 0
  state_class: "measurement"
